import React, { useState } from 'react';
import { Sparkles, Brain, LogOut, BookOpen, Search, ArrowRight } from 'lucide-react';

const StudentDashboard = ({ user, onLogout, onJoinRoom }) => {
  const [roomId, setRoomId] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    if (!roomId.trim()) {
      setError('Please provide a valid Meeting ID.');
      return;
    }

    setLoading(true);

    try {
      // Query room status from the server
      const response = await fetch(`http://localhost:5000/api/rooms/${roomId.trim()}`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.message || 'Meeting room not found. Double check ID.');
      }

      // Proceed to the setup/device test phase
      onJoinRoom(data.roomId);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="dashboard-wrapper animate-fade-in">
      {/* Top Navbar */}
      <header className="dashboard-header glass">
        <div className="logo-group">
          <div className="logo-icon-wrapper">
            <Brain size={22} className="logo-icon animate-pulse" />
          </div>
          <h1>MindBridge AI</h1>
        </div>

        <div className="user-profile-group">
          <span className="role-badge student">
            <BookOpen size={14} />
            SCHOLAR
          </span>
          <span className="user-name">Welcome, {user.name}</span>
          <button onClick={onLogout} className="logout-btn" title="Log Out">
            <LogOut size={18} />
          </button>
        </div>
      </header>

      {/* Main selection panels */}
      <div className="dashboard-double-columns">
        {/* Left Card: Join Meeting (Active) */}
        <div className="dashboard-card glass creator-panel animate-slide-up">
          <div className="card-top">
            <Sparkles className="accent-icon student" size={22} />
            <h3>Join Intelligent Classroom</h3>
          </div>
          <p className="card-desc">
            Enter the Meeting ID generated by your teacher to enter the classroom. The AI assistant will explain topic slides in real time while tracking your attentiveness.
          </p>

          {error && (
            <div className="error-alert animate-fade-in" style={{ marginBottom: '1.5rem' }}>
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="setup-form">
            <div className="setup-form-group">
              <label htmlFor="student-roomId-input">
                <Search size={14} />
                <span>Enter Classroom Meeting ID</span>
              </label>
              <input
                id="student-roomId-input"
                type="text"
                placeholder="e.g. MB-3928"
                value={roomId}
                onChange={(e) => setRoomId(e.target.value)}
                required
              />
            </div>

            <button type="submit" className="gen-btn student setup-submit-btn" disabled={loading}>
              <span>{loading ? 'Verifying Room...' : 'Proceed to Device Setup'}</span>
              <ArrowRight size={16} />
            </button>
          </form>
        </div>

        {/* Right Card: Self Study (Disabled/Mocked) */}
        <div className="dashboard-card glass creator-panel disabled-sandbox animate-slide-up" style={{ opacity: 0.5 }}>
          <div className="card-top">
            <BookOpen className="accent-icon admin" size={22} />
            <h3>Self Study Hub</h3>
          </div>
          <p className="card-desc">
            [Under Development] Compile your own personalized subjects, generate interactive flashcards, and run independent self-assessments.
          </p>
          <div className="disabled-notice">
            <span>Coming Soon in Version 2.0</span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default StudentDashboard;
